# Generated by Django 4.0.2 on 2022-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='month_of_employment',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('Jun', 'Jun'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True),
        ),
    ]
